version: "3.9"
services:
    user-service:
        container_name: user-service
        image: user-service
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9001:9001"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-server:29092
        networks:
            - backend

networks:
    backend:
        external: true